const Router = require("express");
const router = new Router();
const AddtionalEquipment = require("./additionalEquipmentRouter");
const album = require("./albumRouter");
const description = require("./descripitonRouter");
const equipment = require("./equipmentRouter");
const feedback = require("./feedbackRouter");
const guide = require("./guideRouter");
const hotels = require("./hotelRouter");
const images = require("./imagesRouter");
const infoItems = require("./infoItemRouter");
const infos = require("./infoRouter");
const instructor = require("./instructorRouter");
const lift = require("./liftRouter");
const news = require("./newsRouter");
const pass = require("./passRouter");
const review = require("./passRouter");
const room = require("./roomRouter");
const selectTypes = require("./selectTypeRouter");
const service = require("./serviceRouter");
const servicePriceList = require("./servicePriceListRouter");
const tour = require("./tourRouter");
const users = require("./userRouter");

router.use("/additionalEquipment", AddtionalEquipment);
router.use("/album", album);
router.use("/description", description);
router.use("/equipment", equipment);
router.use("/feedback", feedback);
router.use("/guide", guide);
router.use("/hotels", hotels);
router.use("/images", images);
router.use("/infoItems", infoItems);
router.use("/infos", infos);
router.use("/instructor", instructor);
router.use("/lift", lift);
router.use("/news", news);
router.use("/pass", pass);
router.use("/review", review);
router.use("/room", room);
router.use("/selectTypes", selectTypes);
router.use("/service", service);
router.use("/servicePriceList", servicePriceList);
router.use("/users", users);
router.use("/tour", tour);

module.exports = router;
